Repository andela/ah-alpha-frontend, pull requests merged in 2019-02, with the labels that each got.

#8 #162948873 Login Component
  .eslintignore
  .eslintrc
  .gitignore
  package.json
  public/index.html
  src/App.js
  src/App.scss
  src/_helpers/history.js
  src/actions/__test__/Login.action.test.js
  src/actions/loginActions.js
  src/actions/types.js
  src/common/Navbar.js
  src/components/Home.js
  src/components/Login.js
  src/components/Navbar.js
  src/components/authentication/Login.js
  src/components/authentication/__test__/Login.component.test.js
  src/components/authentication/__test__/Login.snapshot.test.js
  src/components/authentication/__test__/__snapshots__/Login.snapshot.test.js.snap
  src/components/containers/login/LoginForm.js
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/store/index.js
  src/redux/store/initialState.js
Labels: finished

#9 #162948871 Users' registration and verification
  .codeclimate.yml
  .eslintignore
  .gitignore
  package.json
  public/index.html
  src/App.js
  src/App.scss
  src/actions/__test__/Login.action.test.js
  src/actions/__test__/authentication.test.js
  src/actions/authentication.js
  src/actions/constants.js
  src/actions/loginActions.js
  src/actions/tempCodeRunnerFile.js
  src/api/postPromise.js
  src/common/Navbar.js
  src/components/authentication/EmailVerification.js
  src/components/authentication/Login.js
  src/components/authentication/Login.test.js
  src/components/authentication/RegistrationForm.js
  src/components/authentication/__test__/__snapshots__/Login.snapshot.test.js.snap
  src/components/authentication/__test__/emailVerification.test.js
  src/components/authentication/__test__/registrationForm.test.js
  src/components/common/Body.js
  src/components/common/Navbar.js
  src/components/containers/login/LoginForm.js
  src/components/containers/registration/Registration.js
  src/components/containers/registration/__test__/registration.test.js
  src/index.scss
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/__test__/registration.test.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/registration.js
  src/redux/store/index.js
  src/setupTests.js
Labels: finished

#11 #162948874 Social Login
  .babelrc
  .eslintrc
  .gitignore
  package.json
  src/App.js
  src/actions/LoginForm.js
  src/actions/loginActions.js
  src/actions/socialAuth/SocialAuthActions.js
  src/actions/socialAuth/__test__/SocialAuthActions.test.js
  src/actions/types.js
  src/assets/css/App.scss
  src/assets/css/SocialAuth.scss
  src/assets/css/index.scss
  src/components/authentication/Login.js
  src/components/authentication/RegistrationForm.js
  src/components/authentication/socialAuth/ButtonInput.js
  src/components/authentication/socialAuth/SuccessComponent.js
  src/components/authentication/socialAuth/__test__/SuccessComponent.test.js
  src/components/containers/socialAuth/SocialAuthComponent.js
  src/components/containers/socialAuth/__test__/SocialAuthComponent.test.js
  src/config/firebase.js
  src/index.js
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/socialAuth/SocialAuthReducer.js
  src/redux/reducers/socialAuth/__test__/SocialAuthReducer.test.js
  src/redux/reducers/socialAuth/index.js
Labels: finished

#12 #162948875 Ft user should view and edit their profile
  .codeclimate.yml
  package.json
  src/App.js
  src/_helpers/history.js
  src/actions/__test__/profileActions.test.js
  src/actions/__test__/profileAxiosAction.test.js
  src/actions/profileActions.js
  src/api/axiosConfig.js
  src/api/image.js
  src/api/profileApi.js
  src/assets/css/App.scss
  src/components/authentication/Login.js
  src/components/authentication/RegistrationForm.js
  src/components/common/Body.js
  src/components/common/Navbar.js
  src/components/common/userOptions.js
  src/components/containers/login/LoginForm.js
  src/components/containers/login/__test__/loginForm.test.js
  src/components/containers/login/__test__/loginFormComponent.test.js
  src/components/containers/profiles/__test__/profile.test.js
  src/components/containers/profiles/__test__/profileContainer.test.js
  src/components/containers/profiles/__test__/profileEditContainer.test.js
  src/components/containers/profiles/profileEdit.js
  src/components/containers/profiles/profiles.js
  src/components/containers/registration/Registration.js
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/__test__/loginData.test.js
  src/redux/reducers/index.js
  src/redux/reducers/loginReducer.js
  src/redux/reducers/profile/__test__/profileReducer.test.js
  src/redux/reducers/profile/profileReducer.js
  src/redux/store/index.js
  src/redux/store/initialState.js
Labels: finished

#10 #162948872 password reset
  src/App.js
  src/actions/axiosConfig.js
  src/actions/forgotPassword.js
  src/actions/resetPasswd.js
  src/actions/types.js
  src/assets/css/App.scss
  src/assets/css/index.scss
  src/assets/css/reset.scss
  src/components/containers/login/LoginForm.js
  src/components/containers/passwordReset/ForgotPassword.js
  src/components/containers/passwordReset/ResetPassword.js
  src/components/containers/passwordReset/__test__/ForgotPassword.test.js
  src/components/containers/passwordReset/__test__/ResetPassword.test.js
  src/components/containers/profiles/profileEdit.js
  src/index.js
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/passwordReset/forgotPassword.js
  src/redux/reducers/passwordReset/passwordReset.js
Labels: finished

#16 #162948876 Get all articles
  .codeclimate.yml
  package.json
  src/App.js
  src/App.scss
  src/actions/getArticlesAction.js
  src/actions/getOneArticleAction.js
  src/actions/types.js
  src/assets/css/App.scss
  src/assets/css/index.scss
  src/components/Home.js
  src/components/Home.test.js
  src/components/SingleArticle.js
  src/components/common/Navbar.js
  src/components/common/userOptions.js
  src/components/containers/articles/Articles.js
  src/components/containers/articles/OneArticle.js
  src/components/containers/articles/__test__/Article.test.js
  src/redux/reducers/__test__/Login.reducer.test.js
  src/redux/reducers/getArticlesReducer.js
  src/redux/reducers/getOneArticleReducer.js
  src/redux/reducers/index.js
  src/redux/store/index.js
Labels: WIP

#17 #162948879 implement pagination
  .codeclimate.yml
  package.json
  src/App.scss
  src/actions/getArticlesAction.js
  src/assets/css/App.scss
  src/assets/css/reset.scss
  src/components/SingleArticle.js
  src/components/common/Navbar.js
  src/components/common/loader.js
  src/components/containers/articles/Articles.js
  src/components/containers/articles/OneArticle.js
  src/components/containers/articles/__test__/Article.test.js
  src/components/containers/profiles/profiles.js
  src/redux/reducers/getArticlesReducer.js
  src/redux/reducers/index.js
Labels: finished, work_in_progress
